global:
  # -- Set additional global labels.
  labels: {}
  # -- Set additional global annotations.
  annotations: {}

apps:
  vader:
    enabled: true
    serviceName: vader-svc
    type: statefulset
    rollingUpdate:
      unavailable:
      surge:
      partition: 3

      
    replicas: 2
    containers:
      vader:
        image:
          # -- Specify the image repository for the container
          repository: luckysideburn/kubeinvaders
          # -- Specify the image tag for the container
          tag: v1.9.6

services:
  vader-svc:
    enabled: true
    appName: vader
    type: NodePort
    clusterIP: None
    ports:
      webui:
        enabled: true
        port: 8080
        protocol: TCP
        nodePort: 8085
        targetPort: 8080

