global:
  # -- Set additional global labels.
  labels: {}
  # -- Set additional global annotations.
  annotations: {}

apps:
  kubevader2:
    enabled: true
    serviceName: foo/web
    type: statefulset
    rollingUpdate:
      unavailable:
      surge:
      partition: 3

      
    replicas: 2
    containers:
      kubevader2:
        image:
          # -- Specify the image repository for the container
          repository: luckysideburn/kubeinvaders
          # -- Specify the image tag for the container
          tag: v1.9.6

services:
  kubevader2:
    enabled: true
    appName: kubevader2
    type: ClusterIP
    clusterIP: None
    ports:
      webui:
        enabled: true
        port: 8080
        protocol: TCP
        nodePort: 
        targetPort: 8080

